# Generated by Django 3.2.18 on 2024-10-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.CharField(db_column='text_title', max_length=20)),
                ('text_body', models.CharField(db_column='text_body', max_length=500)),
                ('creater', models.CharField(db_column='creater', max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(db_column='comment_text', max_length=100)),
                ('commenter', models.CharField(db_column='commenter', max_length=10)),
                ('crate_date', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, to='board.create')),
            ],
        ),
    ]
