# Generated by Django 3.2.18 on 2024-10-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='crate_date',
            new_name='create_date',
        ),
    ]
