# Generated by Django 3.2.18 on 2024-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='contents',
            field=models.TextField(db_column='contents', max_length=1000),
        ),
    ]
