# Generated by Django 3.2.18 on 2024-10-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_crate_date_comment_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
    ]
